# Generated by Django 2.2.1 on 2020-03-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news_part',
            fields=[
                ('news_ID', models.IntegerField(default=0, editable=False, primary_key=True, serialize=False)),
                ('news_title', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('news_content', models.TextField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='setting_prediction',
            fields=[
                ('setting_ID', models.IntegerField(default=0, editable=False, primary_key=True, serialize=False)),
                ('setting_name', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('tooltip', models.TextField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
    ]
