# Generated by Django 2.2.1 on 2020-03-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimicINTapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_text',
            fields=[
                ('text_ID', models.IntegerField(default=0, editable=False, primary_key=True, serialize=False)),
                ('text_title', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('text_content', models.TextField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
    ]
