# Generated by Django 2.2.1 on 2020-04-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimicINTapp', '0002_home_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='output_file',
            fields=[
                ('file_accession', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('file_description', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('file_path', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('rule_id', models.TextField(editable=False, max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
