# Generated by Django 2.2.1 on 2020-04-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimicINTapp', '0003_output_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='pipeline_rule',
            fields=[
                ('rule_id', models.TextField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('rule_order', models.IntegerField(default=0, null=True)),
                ('rule_description', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('rule_duration', models.IntegerField(default=0, null=True)),
                ('log_path', models.TextField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
