# Generated by Django 2.2.1 on 2020-11-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimicINTapp', '0004_pipeline_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_infos',
            fields=[
                ('job_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('run_name', models.CharField(max_length=255)),
                ('target_name', models.CharField(max_length=255)),
                ('query_name', models.CharField(max_length=255)),
                ('about', models.TextField(max_length=65535)),
            ],
        ),
    ]
